name: Laravel CD
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - CD

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, dom, fileinfo, pgsql

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-scripts --no-progress --no-interaction
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Migrate and Seed Database
        run: |
          php artisan optimize
          php artisan migrate --force
          php artisan db:seed --force
        env:
          APP_ENV: production
          DB_CONNECTION: pgsql
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Deploy to Vercel
        run: vercel deploy --yes --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
